image_yscale = 0;
direction = obj_player.direction;
movspd = obj_player.movspd;;

if direction = 0 {
	sprite_index = spr_shieldside;
	image_xscale = -1;
	depth = obj_player.depth - 1;}
if direction = 45 {
	sprite_index = spr_shielddiagup;
	image_xscale = -1;
	depth = obj_player.depth + 1;}
if direction = 90 {
	sprite_index = spr_shieldup;
	image_xscale = 1;
	depth = obj_player.depth + 1;}
if direction = 135 {
	sprite_index = spr_shielddiagup;
	image_xscale = 1;
	depth = obj_player.depth + 1;}
if direction = 180 {
	sprite_index = spr_shieldside;
	image_xscale = 1;
	depth = obj_player.depth - 1;}
if direction = 225 {
	sprite_index = spr_shielddiagdown;
	image_xscale = 1;
	depth = obj_player.depth - 1;}
if direction = 270 {
	sprite_index = spr_shielddown;
	image_xscale = 1;
	depth = obj_player.depth - 1;}
if direction = 315 {
	sprite_index = spr_shielddiagdown;
	image_xscale = -1;
	depth = obj_player.depth - 1;}